apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c" ]
          args: [ "cp /data/config/*.hcl /app/ ; /app/openmetrics-exporter run openmetrics -d /app/" ]
          volumeMounts:
            - name: ome-config-volume
              mountPath: /data/config
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
      volumes:
        - name: ome-config-volume
          configMap:
            name: ome-configs
