apiVersion: v2
name: openmetrics-exporter-chart
description: A Helm chart for openmetrics exporter
type: application
version: 0.1.0
appVersion: "0.18.0"
maintainers:
  - name: Last9
    email: hello@last9.io
    url: https://last9.io/
